[ColorScheme]
# Ordem das 21 roles do QPalette:
# WindowText, Button, Light, Midlight, Dark, Mid, Text, BrightText,
# ButtonText, Base, Window, Shadow, Highlight, HighlightedText, Link,
# LinkVisited, AlternateBase, NoRole, ToolTipBase, ToolTipText, PlaceholderText
active_colors=#ffc8c8c8, #ff141414, #ff262626, #ff1c1c1c, #ff0b0b0b, #ff161616, #ffc8c8c8, #ffffffff, #ffc8c8c8, #ff0b0b0b, #ff0b0b0b, #ff000000, #ffffffff, #ff000000, #ffffffff, #ff8a8a8a, #ff141414, #ff000000, #ff141414, #ffc8c8c8, #ff3d3d3d
inactive_colors=#ffc8c8c8, #ff141414, #ff262626, #ff1c1c1c, #ff0b0b0b, #ff161616, #ffc8c8c8, #ffffffff, #ffc8c8c8, #ff0b0b0b, #ff0b0b0b, #ff000000, #ff262626, #ffc8c8c8, #ffffffff, #ff8a8a8a, #ff141414, #ff000000, #ff141414, #ffc8c8c8, #ff3d3d3d
disabled_colors=#ff3d3d3d, #ff141414, #ff262626, #ff1c1c1c, #ff0b0b0b, #ff161616, #ff3d3d3d, #ffffffff, #ff3d3d3d, #ff0b0b0b, #ff0b0b0b, #ff000000, #ff262626, #ff8a8a8a, #ff3d3d3d, #ff3d3d3d, #ff141414, #ff000000, #ff141414, #ff3d3d3d, #ff3d3d3d
