[Appearance]
custom_palette=true
color_scheme_path=~/.config/qt5ct/mono.conf
standard_dialogs=xdgdesktopportal
style=Fusion
icon_theme=Papirus-Dark

[Fonts]
fixed="JetBrainsMono Nerd Font,10,-1,5,50,0,0,0,0,0"
general="SF Pro Text,11,-1,5,50,0,0,0,0,0"

[Interface]
cursor_flash_time=1000
dialog_buttons_have_icons=0
gui_effects=@Invalid()
menus_have_icons=false
underline_shortcut=1
